# Generated by Django 2.1.5 on 2021-01-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='products_id',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
