# Generated by Django 2.1.5 on 2021-01-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop', '0003_auto_20210123_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_id',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
