# Generated by Django 2.1.5 on 2021-01-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, default='@username', max_length=264),
        ),
    ]
